name: Copy File to Release Branch

on:
  push:
    branches:
      - arduino

jobs:
  copy-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: arduino

    - name: Git initialize work
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Switch to main branch(Modify)
      run: |
        git branch -M main
    
    - name: Modifying file to the desired form
      run: |
        mkdir arduino_code
        find . -maxdepth 1 -type f ! -name 'arduino_code' -exec mv {} arduino_code/ \;
        rm -rf .github
        rm -rf .vscode
    
    - name: Commit to new Arduino code commit
      run: |
        git add .
        git commit -m "Push arduino code"
    
    - name: Fetch previous data
      run: |
        git pull origin main
    
    - name: Push new data to main
      run: |
        git push -u origin main

    
